name: 'Pull request changed files filter'
description: 'Enables conditional execution of workflow job steps considering which files are modified by a pull request.'
author: 'Michal Dorner <dorner.michal@gmail.com>'
inputs:
  githubToken:
    description: 'GitHub Access Token'
    required: true
    default: ${{ github.token }}
  filters:
    description: 'Path to the configuration file or YAML string with filters definition'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  color: blue
  icon: filter