name: 'Paths filter'
description: 'Execute your workflow steps only if relevant files are modified.'
author: 'Michal Dorner <dorner.michal@gmail.com>'
inputs:
  token:
    description: 'GitHub Access Token'
    required: false
    default: ${{ github.token }}
  filters:
    description: 'Path to the configuration file or YAML string with filters definition'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  color: blue
  icon: filter