name: 'Paths Changes Filter'
description: 'Execute your workflow steps only if relevant files are modified.'
author: 'Michal Dorner <dorner.michal@gmail.com>'
inputs:
  token:
    description: 'GitHub Access Token'
    required: false
    default: ${{ github.token }}
  working-directory:
    description: 'Relative path under $GITHUB_WORKSPACE where the repository was checked out.'
    required: false
  ref:
    description: |
      Git reference (e.g. branch name) from which the changes will be detected.
      This option is ignored if action is triggered by pull_request event.
    required: false
  base:
    description: |
      Git reference (e.g. branch name) against which the changes will be detected. Defaults to repository default branch (e.g. master).
      If it references same branch it was pushed to, changes are detected against the most recent commit before the push.
      This option is ignored if action is triggered by pull_request event.
    required: false
  filters:
    description: 'Path to the configuration file or YAML string with filters definition'
    required: true
  list-files:
    description: |
      Enables listing of files matching the filter:
        'none'  - Disables listing of matching files (default).
        'csv'   - Coma separated list of filenames.
                  If needed it uses double quotes to wrap filename with unsafe characters.
        'json'  - Serialized as JSON array.
        'shell' - Space delimited list usable as command line argument list in linux shell.
                  If needed it uses single or double quotes to wrap filename with unsafe characters.
        'escape'- Space delimited list usable as command line argument list in linux shell.
                  Backslash escapes every potentially unsafe character.
    required: false
    default: none
  write-to-files:
    description: |
      Enables writing the lists of matching files to a corresponding file in addition to the output '<filter-name>_files'.
      If set, the action will create the specified file with the list of matching files.
      The file will be written in the format specified by the `list-files` option and named
      after the filter. The path to the file will be output as a variable named `<filter-name>_files_path`.
    required: false
  initial-fetch-depth:
    description: |
      How many commits are initially fetched from base branch.
      If needed, each subsequent fetch doubles the previously requested number of commits
      until the merge-base is found or there are no more commits in the history.
      This option takes effect only when changes are detected using git against different base branch.
    required: false
    default: '100'
  predicate-quantifier:
    description: |
      allows to override the "at least one pattern" behavior to make it so that all of the patterns have to match or otherwise the file is excluded.
    required: false
    default: 'some'
outputs:
  changes:
    description: JSON array with names of all filters matching any of changed files
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  color: blue
  icon: filter
