name: "Pull Request Verification"
on:
  pull_request:
    paths-ignore: [ '*.md' ]
    branches:
      - master
      - '**'
  push:

jobs:
  comment:
    if: github.event.pull_request
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./@numstat
      id: filter
      with:
        filters: |
          src:
            - "src/**"
          tests:
            - "__tests__/**"
        - name: Find Comment
    - uses: peter-evans/find-comment@v1
      id: find-comment
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: '<!-- Paths Filter Diff Stat -->'
    - uses: peter-evans/create-or-update-comment@v1
      id: create-or-update-comment
      with:
        comment-id: ${{ steps.find-comment.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          <!-- Paths Filter Diff Stat -->
          ${{ steps.run-git-diff.outputs.src_addition_count }}
          ${{ steps.run-git-diff.outputs.tests_addition_count }}
          ${{ steps.run-git-diff.outputs.any_addition_count }}
        edit-mode: replace